/*
* Autenticacion y autorizacion
*/
POST
http://localhost:4000/api/auth/signin
http://localhost:4000/api/auth/signup

/*
* Gestion de usuarios
*/
GET
Obtiene todos los usuarios{email, password}
http://localhost:4000/api/users
Obtiene el usuario{email, password} por el id
http://localhost:4000/api/users/:id
Usuarios por el rol
role: [moderator, economist, manager, user]
http://localhost:4000/api/users/get/:${role}
PUT
Edita el usuario por el id
http://localhost:4000/api/users/:id
DELETE
Invalida el usuario{email, password}
http://localhost:4000/api/users/:id

/*
* Gestion de eventos
*/
GET
http://localhost:4000/api/events
http://localhost:4000/api/events/:id